server:
  port: 8080
  # servlet:
    # context-path : /boot

spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    content-type: text/html
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.weibin.springboot
