package cn.weibin.springboot.entity;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.id
     *
     * @mbggenerated Sun Aug 18 22:20:20 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.role_code
     *
     * @mbggenerated Sun Aug 18 22:20:20 CST 2019
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.user_name
     *
     * @mbggenerated Sun Aug 18 22:20:20 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.password
     *
     * @mbggenerated Sun Aug 18 22:20:20 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.title
     *
     * @mbggenerated Sun Aug 18 22:20:20 CST 2019
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbggenerated Sun Aug 18 22:20:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbggenerated Sun Aug 18 22:20:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.role_code
     *
     * @return the value of member.role_code
     *
     * @mbggenerated Sun Aug 18 22:20:20 CST 2019
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.role_code
     *
     * @param roleCode the value for member.role_code
     *
     * @mbggenerated Sun Aug 18 22:20:20 CST 2019
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.user_name
     *
     * @return the value of member.user_name
     *
     * @mbggenerated Sun Aug 18 22:20:20 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.user_name
     *
     * @param userName the value for member.user_name
     *
     * @mbggenerated Sun Aug 18 22:20:20 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.password
     *
     * @return the value of member.password
     *
     * @mbggenerated Sun Aug 18 22:20:20 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.password
     *
     * @param password the value for member.password
     *
     * @mbggenerated Sun Aug 18 22:20:20 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.title
     *
     * @return the value of member.title
     *
     * @mbggenerated Sun Aug 18 22:20:20 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.title
     *
     * @param title the value for member.title
     *
     * @mbggenerated Sun Aug 18 22:20:20 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}